name: FlowChat
version: '${version}'
main: computer.brads.flowchat.spigot.FlowChatSpigot
description: Regex-powered chat processor
authors: [bradcarnage]
website: https://github.com/bradcarnage/FlowChat
softdepend: [packetevents]
commands:
  flowchat:
    description: FlowChat admin commands
    usage: /flowchat <reload|toggle>
    permission: flowchat.admin
permissions:
  flowchat.admin:
    description: Manage FlowChat
    default: op
