modLoader="javafml"
loaderVersion="[47,)"
license="GPL-3.0"

[[mods]]
modId="flowchat"
version="${version}"
displayName="FlowChat"
description="Regex-powered chat processor"
authors="bradcarnage"
displayURL="https://github.com/bradcarnage/FlowChat"

[[dependencies.flowchat]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="CLIENT"

[[dependencies.flowchat]]
modId="minecraft"
mandatory=true
versionRange="[1.21.11,1.22)"
ordering="NONE"
side="CLIENT"
