plugins {
    id 'java'
}

allprojects {
    group = project.maven_group
    version = project.mod_version

    repositories {
        mavenCentral()
        maven { url = 'https://repo.codemc.io/repository/maven-releases/' }
        maven { url = 'https://repo.codemc.io/repository/maven-snapshots/' }
        maven { url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/' }
        maven { url = 'https://repo.papermc.io/repository/maven-public/' }
        maven { url = 'https://oss.sonatype.org/content/repositories/snapshots/' }
    }
}

subprojects {
    apply plugin: 'java'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
        withSourcesJar()
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.release = 17
    }

    jar {
        from(rootProject.file('LICENSE')) {
            rename { "${it}_${project.base.archivesName.get()}" }
        }
    }
}
