# Build
org.gradle.jvmargs=-Xmx2G

# Mod/Plugin
mod_version=2.1.0
maven_group=computer.brads.flowchat
mod_id=flowchat

# Minecraft
minecraft_version=1.21.6

# Fabric
yarn_mappings=1.21.6+build.1
fabric_loader_version=0.19.2
fabric_api_version=0.128.2+1.21.6
fabric_loom_version=1.10.5

# PacketEvents
packetevents_version=2.7.0

# Spigot
spigot_api_version=1.21.4-R0.1-SNAPSHOT

# Velocity
velocity_api_version=3.4.0-SNAPSHOT

# Forge
forge_version=54.1.16

# NeoForge
neoforge_version=21.4.157

# Adventure
adventure_version=4.17.0
