plugins {
    id 'java'
    id 'com.gradleup.shadow' version '8.3.5'
}

base {
    archivesName = 'flowchat-spigot'
}

dependencies {
    implementation project(':common')
    implementation project(':packetevents-common')
    compileOnly "org.spigotmc:spigot-api:${rootProject.spigot_api_version}"
    compileOnly "com.github.retrooper:packetevents-spigot:${rootProject.packetevents_version}"
    compileOnly "net.kyori:adventure-api:${rootProject.adventure_version}"
}

shadowJar {
    archiveClassifier.set('')
    relocate 'computer.brads.flowchat.core', 'computer.brads.flowchat.spigot.libs.core'
    relocate 'computer.brads.flowchat.packet', 'computer.brads.flowchat.spigot.libs.packet'
    minimize()
}

processResources {
    filesMatching('plugin.yml') {
        expand(version: rootProject.version)
    }
}

tasks.assemble.dependsOn tasks.shadowJar
