buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net/' }
        mavenCentral()
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.1-SNAPSHOT'
    }
}

apply plugin: 'net.minecraftforge.gradle.forge'

version = '2.1.2'
group = 'computer.brads.flowchat'

archivesBaseName = 'flowchat-forge'

sourceCompatibility = JavaVersion.VERSION_1_8
targetCompatibility = JavaVersion.VERSION_1_8

minecraft {
    version = '1.8.9-11.15.1.2318-1.8.9'
    runDir = 'run'
    mappings = 'stable_20'
}

repositories { mavenCentral() }

dependencies {
    compile 'com.google.code.gson:gson:2.8.9'
    compile 'org.slf4j:slf4j-api:1.7.36'
}

sourceSets {
    main {
        java {
            srcDir '../common/src/main/java'
            srcDir 'src/main/java'
        }
        resources { srcDir 'src/main/resources' }
    }
}

processResources {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    inputs.property 'version', project.version
    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand 'version': project.version
    }
    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}
