plugins {
    id 'java'
    id 'net.neoforged.moddev' version '2.0.+'
}

version = '2.1.2'
group = 'computer.brads.flowchat'

base {
    archivesName = 'flowchat-neoforge'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
}

neoForge {
    version = '21.9.16-beta'

    mods {
        flowchat {
            sourceSet sourceSets.main
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.google.code.gson:gson:2.11.0'
}

sourceSets {
    main {
        java {
            srcDir '../common/src/main/java'
            srcDir 'src/main/java'
        }
        resources {
            srcDir 'src/main/resources'
        }
    }
}

processResources {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    filesMatching('META-INF/neoforge.mods.toml') {
        expand(version: project.version)
    }
}

sourcesJar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
